#!/bin/bash

GPG_KEY=E3556535

# Software source
SOFTWARE_SOURCE=$(cd "$(pwd -P)/src"; pwd)

# Home dir, root file system for this package
HOME_DIR=$(cd "$(pwd -P)/.."; pwd)

# Debian packaging dir
DEB_PACKAGING_DIR=$(pwd)

#Dont sign the package
#dpkg-buildpackage -uc -us -tc -rfakeroot

# Build the package
dpkg-buildpackage -uc -tc -rfakeroot

#Gpg sign the package
dpkg-sig --sign builder -k ${GPG_KEY} ../*.deb
